version: '2'
#env_file: .env
services: 
  app:
    #image: joomla:3.6.2-apache-php7
    #image: joomla:3.6.2-apache
    build: ./app
    links:
     - mysql
    ports:
     - "${APP_PORT}:80"
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - VIRTUAL_HOST=${VIRTUAL_HOST}
     - VIRTUAL_PORT=${APP_PORT}
     - LETSENCRYPT_HOST=${VIRTUAL_HOST}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - web
      - internalnet
    volumes:
     - ./code:/var/www/html
  
  mysql:
    image: mysql:5.7.28
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     #- MYSQL_DATABASE=joomla
    volumes:
     - ./database:/var/lib/mysql
     - ./mysql-xfer:/root/xfer
   networks:
      - internalnet
 
  smtpout:
    image: namshi/smtp
    restart: always
    networks:
      - internalnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    links:
     - mysql
    ports:
     - "${PHPMYADMIN_PORT}:80"
    environment:
     - PMA_HOST=mysql
     - VIRTUAL_HOST=phpmyadmin.${VIRTUAL_HOST}
     - VIRTUAL_PORT=${PHPMYADMIN_PORT}
     - LETSENCRYPT_HOST=phpmyadmin.${VIRTUAL_HOST}
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - internalnet
      - web

networks: 
  web:
    external:
      name: ${PROXY_NETWORK}
  internalnet: